[package]
name = "libretro-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
ggez = "0.9.3"
libc = "0.2.150"
libloading = "0.8.1"
libretro-sys = "0.1.1"
once_cell = "1.18.0"
rodio = "0.17.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
